package core.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

    public M setPkid(Integer pkid) {
        set("pkid", pkid);
        return (M) this;
    }

    public Integer getPkid() {
        return get("pkid");
    }

    public M setBrand(String brand) {
        set("brand", brand);
        return (M) this;
    }

    public String getBrand() {
        return get("brand");
    }

    public M setUrl(String url) {
        set("url", url);
        return (M) this;
    }

    public String getUrl() {
        return get("url");
    }

    public M setName(String name) {
        set("name", name);
        return (M) this;
    }

    public String getName() {
        return get("name");
    }

    public M setImg(String img) {
        set("img", img);
        return (M) this;
    }

    public String getImg() {
        return get("img");
    }

    public M setMaterial(String material) {
        set("material", material);
        return (M) this;
    }

    public String getMaterial() {
        return get("material");
    }

    public M setColor(String color) {
        set("color", color);
        return (M) this;
    }

    public String getColor() {
        return get("color");
    }

    public M setSize(String size) {
        set("size", size);
        return (M) this;
    }

    public String getSize() {
        return get("size");
    }

    public M setRef(String ref) {
        set("ref", ref);
        return (M) this;
    }

    public String getRef() {
        return get("ref");
    }

    public M setPrice(String price) {
        set("price", price);
        return (M) this;
    }

    public String getPrice() {
        return get("price");
    }

    public M setClassification(String classification) {
        set("classification", classification);
        return (M) this;
    }

    public String getClassification() {
        return get("classification");
    }

    public M setLanguage(String language) {
        set("language", language);
        return (M) this;
    }

    public String getLanguage() {
        return get("language");
    }

    public M setTags(String tags) {
        set("tags", tags);
        return (M) this;
    }

    public String getTags() {
        return get("tags");
    }

    public M setHkPrice(String hkPrice) {
        set("hk_price", hkPrice);
        return (M) this;
    }

    public String getHkPrice() {
        return get("hk_price");
    }

    public M setEnPrice(String enPrice) {
        set("en_price", enPrice);
        return (M) this;
    }

    public String getEnPrice() {
        return get("en_price");
    }

    public M setEurPrice(String eurPrice) {
        set("eur_price", eurPrice);
        return (M) this;
    }

    public String getEurPrice() {
        return get("eur_price");
    }

    public M setIntroduction(String Introduction) {
        set("Introduction", Introduction);
        return (M) this;
    }

    public String getIntroduction() {
        return get("Introduction");
    }

    public M setCode(String code) {
        set("code", code);
        return (M) this;
    }

    public String getCode() {
        return get("code");
    }

}
