package core.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductCrawler<M extends BaseProductCrawler<M>> extends Model<M> implements IBean {

	public void setPkid(Integer pkid) {
		set("pkid", pkid);
	}

	public Integer getPkid() {
		return get("pkid");
	}

	public void setBrand(String brand) {
		set("brand", brand);
	}

	public String getBrand() {
		return get("brand");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setImg(String img) {
		set("img", img);
	}

	public String getImg() {
		return get("img");
	}

	public void setMaterial(String material) {
		set("material", material);
	}

	public String getMaterial() {
		return get("material");
	}

	public void setColor(String color) {
		set("color", color);
	}

	public String getColor() {
		return get("color");
	}

	public void setSize(String size) {
		set("size", size);
	}

	public String getSize() {
		return get("size");
	}

	public void setRef(String ref) {
		set("ref", ref);
	}

	public String getRef() {
		return get("ref");
	}

	public void setPrice(String price) {
		set("price", price);
	}

	public String getPrice() {
		return get("price");
	}

	public void setClassification(String classification) {
		set("classification", classification);
	}

	public String getClassification() {
		return get("classification");
	}

	public void setLanguage(String language) {
		set("language", language);
	}

	public String getLanguage() {
		return get("language");
	}

	public void setTags(String tags) {
		set("tags", tags);
	}

	public String getTags() {
		return get("tags");
	}

	public void setHkPrice(String hkPrice) {
		set("hk_price", hkPrice);
	}

	public String getHkPrice() {
		return get("hk_price");
	}

	public void setEnPrice(String enPrice) {
		set("en_price", enPrice);
	}

	public String getEnPrice() {
		return get("en_price");
	}

	public void setEurPrice(String eurPrice) {
		set("eur_price", eurPrice);
	}

	public String getEurPrice() {
		return get("eur_price");
	}

	public void setIntroduction(String Introduction) {
		set("Introduction", Introduction);
	}

	public String getIntroduction() {
		return get("Introduction");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return get("code");
	}

}
